camel:
  springboot:
    name: ScaleAPITxCatalogueService
  
  component:
    servlet:
      mapping:
        # Important: must match any proxy request from API Gateway
        contextPath: /*
        
  dataformat:
    json-jackson:
      object-mapper: jacksonObjectMapper
      disable-features: FAIL_ON_EMPTY_BEANS
          
logging:
  level:
    uk.gov.crowncommercial.dsd.api.catalogue: DEBUG
    org.apache.camel: DEBUG
    org.springframework: INFO
    org.apache.tomcat: INFO
    org.apache.catalina: INFO
    org.neo4j.ogm: INFO
    
server:
  port: 9030
  tomcat:
    accesslog:
      enabled: true

# Route configuration
api:
  paths:
    base: /catalogue
    list-products: /products
    get-product: /products/{id}
    
# Spree
spree:
  api:
    url: https://dev.scale-bat-backend.alb.crowncommercial.gov.uk
    paths:
      base: /api/v2/storefront
      list-products: /products
      get-product: /products/{id}
      
---
spring:
  profiles: local
camel:
  component:
    servlet:
      mapping:
        # Mimic API Gateway path prefix (allows switching envs between local and AWS in Postman)
        contextPath: /catalogue-service/*
      